{
  "hash": "457e2522a52a4a392fdabade6701bb61",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Ten -- Point Estimation # Title of the document\n\n# Bibliography Details\nbibliography: Lab10References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab10WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n\n# Lab 8 Notes\n\n##  Altham's Multiplicative Binomial Distribution\n\nThe PMF for Altham's Multiplicative Binomial Distribution is\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}.$$ \nJust so we start on the same page, I have included my `R` function for computing probability using this distribution.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbinom <- function(x, size, prob, theta){\n  normalizing.constant <- 0\n  for(j in 0:size){\n    normalizing.constant <- normalizing.constant + \n      choose(size, j) * prob^j * (1-prob)^(size-j) * theta^(j*(size-j))\n  }\n  # Probability Mass at x=x\n  (1/normalizing.constant) *\n    choose(size, x) * prob^x * (1-prob)^(size-x) * theta^(x*(size-x)) *\n      (x>=0)*(x<=size)\n}\n```\n:::\n\n\n \\normalsize\n\n# Altham's Multiplicative Beta Binomial Distribution\nThe PMF for Altham's Multiplicative Beta Binomial Distribution is\n$$f_X(x) = \\left[\\int_{0}^1 \\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right) dp\\right]I(x \\in \\{0, 1, ..., n\\})$$\n\nJust so we start on the same page, I have included my `R` function for computing probability using this distribution.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbbinom.single <- function(x, size, alpha, beta, theta){\n    integrand <- function(p) {\n    sapply(p, # integrate will pass in a vector, so we use sapply to apply the following\n           function(p_val){\n             # f(x|p) * f(p|alpha, beta)\n             daltbinom(x, size, p_val, theta) * dbeta(p_val, alpha, beta)\n           }\n    )\n  }\n  # Probability Mass at x=x\n  # integrate(integrand, lower = 0, upper = 1)$value * (x>=0)*(x<=size)\n  # I shrink the bounds below to avoid log(0)=-infinty\n  # I use try() to catch when there is an error and avoid crashing\n  res <- try(integrate(integrand, lower = 1e-7, upper = 1 - 1e-7)$value * \n                  (x>=0)*(x<=size), \n             silent = TRUE)\n  # If there is an error, return a near-zero probability\n  if(inherits(res, \"try-error\")) return(0.1^6)\n  \n  res\n}\n# Write a function that works on a vector\ndaltbbinom <- function(x, size, alpha, beta, theta){\n  sapply(X=x, FUN=daltbbinom.single, size=size, alpha=alpha, beta=beta, theta=theta)\n}\n```\n:::\n\n\n \\normalsize\n\n# Question 1\n\nIn Lab 8, we use Altham's Multiplicative Binomial Distribution. Your job was to interpret the impact of $\\theta$ in that equation. In this lab, we will model the number of legs won in a best of eleven (first to six) match. \n\nTo help us think about the interpretation, something that was challenging before, let's try something a little more manageable.\n\n## Part a\nSuppose a player has a 50\\% chance of winning a specific leg, that is let $p=0.50$. Let's look at the probability they win ($x=6$) legs in the match. Compute this probability over a sequence from $\\theta=0.5$ to $\\theta=1.5$ and plot it using a line where the $x$-axis is $\\theta$ and the $y$-axis is $P(X=6)$.\n\nsolution:\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nlibrary(tidyverse) \n\n# created sequence of thetas\nthetas <- seq(from = 0.5, to = 1.5, by = 0.001)\n\n# created probabilities using daltbinom function from 1.1\nprobabilities <- sapply(thetas, function(theta){\n  daltbinom(x = 6, size = 11, prob = 0.50, theta = theta)\n})\n\n# created dataframe consisting of my thetas and probabilities\ndataframe = data.frame(new_theta = thetas, prob = probabilities)\n\n# created plot\nggplot(dataframe) +\n  geom_line(aes(x = new_theta, y = prob)) +\n  xlab(\"theta\") +\n  ylab(\"P(X = 6)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![The probability of winning exactly 6 legs in a best-of-eleven match](Lab10WriteUp_files/figure-html/fig-AlthamsBinom-1.png){#fig-AlthamsBinom fig-align='center' width=480}\n:::\n:::\n\n\n \\normalsize\n\n## Part b\nNow, plot Altham's Multiplicative Binomial Distribution under the same parameters with $\\theta=0.50$, $\\theta=1$, and $\\theta=1.5$. Use `ncol=1` in `facet_wrap()` to plot the PMFs in a single column for comparing.\n\nsolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) \nlibrary(patchwork)\n\n# created a function for making my plots\nplot_function <- function(theta) {\n  x_values <- 0:11\n\n\n# created probabilities using daltbinom function from 1.1\n  probabilities <- sapply(x_values, function(x){\n    daltbinom(x = x, size = 11, prob = 0.50, theta = theta)\n  })\n\n# created dataframe consisting of my thetas and probabilities\n  dataframe = data.frame(x = x_values, prob = probabilities)\n\n# created plot\n  ggplot(dataframe) +\n    geom_linerange(aes(x = x, ymin = 0, ymax = prob)) +\n    labs(title = paste(\"Theta =\", theta),\n    x = \"Number of Wins\",\n    y = \"Probability\") +\n    theme_bw()\n}\n\n# used patchwork to plot the three plots next to each other\nplot_function(0.5) | plot_function(1) | plot_function(1.5)\n```\n\n::: {.cell-output-display}\n![](Lab10WriteUp_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\n## Part c\nWhat is your best assessment of what $\\theta$ is doing in this setting. Consider when a 6-0 blowout is most likely, and when a 5-6 nail-biter is most likely. Note here we should treat the match as a fixed $n=11$ as we did for $n=3$ in Lab 8.\\\n**Note:** In lab 8, we saw that small $\\theta$ meant wins came in bunches (clumped together), so there were more 2-0 wins in a best of three series.\n\nSolution:\nA game where a 6-0 blowout is most likely is when the theta is equal to 0.5 as the probabilities are highest at 0 or 11 wins. A game where a 5-6 nail biter is most likely is probably when theta is equal to 1.5 as the probabilities are highest at 5 and 6 wins.\n\n# Question 2\n\n## Part a\nAltham's Multiplicative Binomial Distribution does not typically simplify to the clean $E(X)=np$ seen in the Binomial distribution, unless $\\theta = 1$. Write out the expression that would need to be solved to find $E(X^k)$, and then write a function that computes it given the proposed parameter values $p$ (`prob`) and $\\theta$ (`theta`).\n\nSolution: \n$$E(X^k) = \\sum_{x \\in S} x^k f_X(x)$$\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# created function for observations portion\nE_altbinom_k <- function(k, size, prob, theta){\n  x_values <- 0:size\n\n# created function for proportion of obs = x portion\n  probabilities <- daltbinom(x = x_values, size = size, prob = prob, theta = theta)\n\n# combined the two portions to get my E(x^k)\n  sum((x_values^k) * probabilitiess)\n}\n```\n:::\n\n\n \\normalsize\n\n## Part b\nDescribe how you can use your answer to part a to find Method of Moments estimates for the parameters $p$ and $\\theta$ for Altham's Multiplicative Binomial Distribution based on data.\n\nSolution:\nTo find method of moments estimates for the parameters, p and theta, I would pass data through the function I created above and compute the k sample moments. I would then find the expected values or population moments by using the function and then set the sample moments equal to the population moments to solve for the parameters. I would set this up for each power from x^1 to x^k and then solve the system of equations.\n\n## Part c\nWrite a function that computes the log-likelihood for Altham's Multiplicative Binomial Distribution, given data (`x`) and proposed parameter values $p$ (`prob`) and $\\theta$ (`theta`).\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# created log likelihood function\nloglikelihood_altbinom <- function(parameters, x, n){\n  p <- parameters[1]\n  theta <- parameters[2]\n\n# created function for probabilities\n  probabilities <- daltbinom(x, n, p, theta)\n\n# summation to calculate log likelihood\n  loglikelihood <- sum(log(probabilities))\n  return(loglikelihood)\n}\n```\n:::\n\n\n \\normalsize\n\n## Part d\nDescribe how you can use your answer to part c to find Maximum Likelihood estimates for the parameters $p$ and $\\theta$ for Altham's Multiplicative Binomial Distribution based on data.\n\nSolution:\nTo find the maximum likelihood estimates I would take data and plug it into my function to multiply the probabilities of each observation together (\"and\" probability). If many probabiltiies between 0 and 1 are getting multiplied together, the resulting probability will be smaller so we take the log likelihood because it is easier to see the results. The goal is to find the parameters that make the observed data most probable so we optimize to find parameters that yield the highest combined probability of all of the observations. \n\n# Lab 10\nPeter \"Snakebite\" Wright is a two-time Professional Darts Corporation World Champion (2020, 2022) and a former World No. 1. He is one of the sport's most decorated players, winning nearly 50 PDC titles including the World Matchplay, UK Open, and multiple European Championships. \n\nIn 2024, he made The Premier League -- a league involving the eight best players that runs every Thursday night from February to May. In this season, he won two of eighteen matches, securing only four points. The spread in legs won was -43, meaning he lost 43 more legs than he won. This performance was rather quite bad. He was soundly trounced in almost all his match ups. \n\n\nThe 2024 standings are below:\n\n| Rank | Player             |\n|:-----|:-------------------|\n| 1    |Luke Littler        |\n| 2    |Luke Humphries      |\n| 3    |Michael van Gerwen  |\n| 4    |Michael Smith       |\n| 5    |Nathan Aspinall     |\n| 6    |Rob Cross           |\n| 7    |Gerwyn Price        |\n| 8    |Peter Wright        |\n\n\n## Summarize the 2024 Data\n\nIn `pdc2024.csv`, I have provided the data for the 2024 Premier League season. There are a few data cleaning steps to consider.\n\n  * Remove any matches with no `Score` (e.g., a bye or walkover)\n  * Nights 1 through 16 are best of 11 (first to 6), but the playoffs are extended. For consistency, keep nights 1 through 16 only.\n  * Make two columns `WinnerLegs` and `LoserLegs` that keep track of the number of legs each player has won\n  \n  Summarize the data. What do the data tell us about the breakdown of the results?\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\npdc_data <- read.csv(\"pdc2024.csv\")\npdc_cleaned <- pdc_data |>\n  filter(Score != \"w/o\") |> # removed walkovers\n  mutate(Night = as.numeric(Night)) |> # made night column all numbers instead of strings\n  filter(Night <= 16) |> # kept only nights 1-16\n  separate(Score, into = c(\"WinnerLegs\", \"LoserLegs\"), sep = \"-\", convert = TRUE) \n  # created two new columns \"WinnerLegs\" and \"LoserLegs\" that keep track of the number of legs each player has won\n\n# created summary statistics table\npdc_cleaned |>\n  count(WinnerLegs, LoserLegs) |>\n  mutate(propotion = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  WinnerLegs LoserLegs  n  propotion\n1          6         1  6 0.05405405\n2          6         2 16 0.14414414\n3          6         3 30 0.27027027\n4          6         4 28 0.25225225\n5          6         5 31 0.27927928\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\n# created x-axis labels\nplot_data <- pdc_cleaned |>\n  count(WinnerLegs, LoserLegs) |>\n  mutate(proportion = n / sum(n),\n         ScoreLabel = paste(WinnerLegs, \"-\", LoserLegs, sep = \"\"))\n\n# created order of x-axis score labels\nlabel_order <- c(\"6-5\", \"6-4\", \"6-3\", \"6-2\", \"6-1\", \"6-0\")\nplot_data <- plot_data |>\n  mutate(ScoreLabel = factor(ScoreLabel, levels = label_order))\n\n# created the plot\nggplot(plot_data, aes(x = ScoreLabel, y = proportion)) +\n  geom_col(fill = \"darkorchid2\", alpha = 0.8) +\n  labs(x = \"Match Score (Winner-Loser)\",\n       y = \"Proportion of Matches\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Distribution of match scorelines in the 2024 Premier League Darts season](Lab10WriteUp_files/figure-html/fig-2024-Darts-Summary-1.png){#fig-2024-Darts-Summary fig-align='center' width=480}\n:::\n:::\n\n\n \\normalsize\n\nThe most common score was 6-5 with about 28% of games ending with that score followed closely by 6-4 and 6-3, meaning most games were competetive. Blowouts where pretty infrequent, at least in comparison to close games. \n\n## Altham's Multiplicative Binomial Distribution\nFor each player in the 2024 season, use the number of legs won in each match to compute maximium likelihood estimates for $p$ and $\\theta$. \\\n**Note**: The \"for each\" here can be done more efficiently with a function or a loop!\n\n* Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner's legs and sometimes from the loser's legs.\n* Find the MLE for the player using this data. Ensure to report $p$ and $\\theta$ for each player in a nicely formatted table.\\\n**Note:** In Lecture on Monday, we used transformations to restrict how `optim()` searches the parameter space. For example, here, you might consider\n`p <- 1/(1+exp(-par[1]))` and `theta <- exp(par[2])`.\n* Make comments about the MLEs in the context of the standings.\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Created function to get the number of legs won by the player\nplayer_legs <- function(data, player_name){\n  new_data <- data |> \n    mutate(LegsWon = ifelse(Winner == player_name, WinnerLegs, LoserLegs)) |>\n    filter(Winner == player_name | Loser == player_name)\n  new_data$LegsWon\n}\n\n# created loglikelihood function:\nloglikelihood <- function(par, x, n = 11, neg = FALSE){\n  # restrict how optim() searches the parameter space (from lab) \n  p <- 1 / (1 + exp(-par[1])) # p between 0 and 1\n  theta <- exp(par[2]) # theta positive\n  ll <- sum(log(daltbinom(x, n, p, theta)))\n  # Return negative if needed\n  ifelse(neg, -ll, ll)\n}\n\n# created MLE function for one player \nMLE <- function(x){\n  estimate <- optim(par=c(0,0), fn=loglikelihood, x=x, neg=TRUE) #same method from class notes\n  p_player <- 1 / (1 + exp(-estimate$par[1])) # p between 0 and 1\n  theta_player <- exp(estimate$par[2]) # theta positive\n  return(c(p = p_player, theta = theta_player))\n}\n\n# created vector of all winners and losers and then used unique function to get rid of repeats\nplayers <- unique(c(pdc_cleaned$Winner, pdc_cleaned$Loser))\n\n#created initialized vectors\np_values <- numeric(length(players))\ntheta_values <- numeric(length(players))\n\n# created for loop to get estimates for each player.\nfor(i in 1:length(players)){\n  # used functions created above\n  x <- player_legs(pdc_cleaned, players[i])\n  estimate <- MLE(x)\n  # updated the initialized vectors\n  p_values[i] <- estimate[\"p\"]\n  theta_values[i] <- estimate[\"theta\"]\n\n# created dataframe with all the estimates\nresults <- data.frame(Player = players,\n                      p = p_values,\n                      theta = theta_values)\n}\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Player         p     theta\n1          Rob Cross 0.3953916 1.0142934\n2       Gerwyn Price 0.3825388 1.0196391\n3      Michael Smith 0.4259674 1.0473321\n4       Luke Littler 0.4690119 1.3159602\n5 Michael van Gerwen 0.4313584 1.0230330\n6     Luke Humphries 0.4607536 1.2046380\n7    Nathan Aspinall 0.4030414 1.1863131\n8       Peter Wright 0.3171264 0.9890277\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe players at the top of the 2024 standings shown above have the highest p values (Littler with 0.469 and Humphries with 0.461), meaning they win more and win a higher proportion of legs. A player like Peter Wright has the lowest p value and is last in the standings, meaning he wins fewer legs on average. Players like Luke Littler and Luke Humphries have higher thetas (1.316 and 1.205 respectively). This likely means that their games closer and more competetive (closer to 6-5 or 6-4) where as someone like Peter Wright has a lower theta (0.989) implying that his games are closer to blowouts, with him likely losing more often then not based off his p value and the standings\n\n\n## Altham's Multiplicative Beta Binomial Distribution\n\nFor each player in the 2024 season, use the number of legs won in each match to compute maxmium likelihood estimates for $p$ and $\\theta$.\\\n**Note**: The \"for each\" here can be done more efficiently with a function or a loop!\n\n* Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner's legs and sometimes from the loser's legs.\n* Find the MLEs for the player using this data. Ensure to report $\\alpha$, $\\beta$, and $\\theta$ for each player in a nicely formatted table.\\\n**Note 1**: Due to the computational complexity of `integrate()`, you should compute the logged probability for `0:6` once and add them according to the data in each player's vector.\n**Note 2**: In Lecture on Monday, we used transformations to restrict how `optim()` searches the parameter space.\n* Plot the underlying Beta($\\alpha$, $\\beta$) distribution for each player. \\\n**Note**: Add the mean and variance of the Beta to the table of MLEs. Recall\n\\begin{align*}\n E(X)   &= \\frac{\\alpha}{\\alpha+\\beta}\\\\\n sd(X) &= \\sqrt{\\frac{\\alpha\\beta}{(\\alpha+\\beta)^2(\\alpha+\\beta+1)}}\n\\end{align*}\n* Make comments about the MLEs in the context of the standings.\\\n**Note**: The players alternate who throws first in a leg has the mathematical \"head start\" to reach a finish before their opponent can take another turn. Players alternate who throws first with each leg.\n\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Created function to get the number of legs won by the player (copied from 5.2)\nplayer_legs <- function(data, player_name){\n  new_data <- data |> \n    mutate(LegsWon = ifelse(Winner == player_name, WinnerLegs, LoserLegs)) |>\n    filter(Winner == player_name | Loser == player_name)\n  new_data$LegsWon\n}\n\n# created function to get log of probabilities\nlog_probs <- function(x_values, n, alpha, beta, theta){\n  # created function to get normal probabilities\n  probabilities <- sapply(x_values, function(x){\n    daltbbinom(x, n, a = alpha, b = beta, theta = theta)\n  })\n  # took log of probabilities\n  log(probabilities)\n}\n\n# created loglikelihood function:\nbbloglikelihood <- function(par, x, n = 11, neg = FALSE){\n  # restrict how optim() searches the parameter space (from lab). Make sure all params are positive (use exp) \n  alpha <- exp(par[1]) \n  beta <- exp(par[2])\n  theta <- exp(par[3])\n  x_values <- 0:6\n  # used log probs function above to get log probs\n  log_prob <- log_probs(x_values, n, alpha, beta, theta)\n  # summed log probs like I did in 5.2 for each observation. Had to use x+1 to go through the x values \n  ll <- sum(log_prob[x+1])\n  # Return negative if needed\n  ifelse(neg, -ll, ll)\n}\n\n# created MLE function for one player \nbbMLE <- function(x){\n  estimate <- optim(par=c(0,0,0), fn=bbloglikelihood, x=x, neg=TRUE) # same as 5.2 with one more parameter\n  alpha_player <- exp(estimate$par[1]) # alpha must be positive\n  beta_player <- exp(estimate$par[2]) # beta must be positive\n  theta_player <- exp(estimate$par[3]) # theta must be positive\n  # returned same as MLE function in 5.2\n  return(c(alpha = alpha_player, beta = beta_player, theta = theta_player))\n}\n\n# created vector of all winners and losers and then used unique function to get rid of repeats\nplayers <- unique(c(pdc_cleaned$Winner, pdc_cleaned$Loser))\n\n#created initialized vectors\nalpha_values <- numeric(length(players))\nbeta_values <- numeric(length(players))\ntheta_values <- numeric(length(players))\n\n# created for loop to get estimates for each player.\nfor(i in 1:length(players)){\n  # used functions created above\n  x <- player_legs(pdc_cleaned, players[i])\n  estimate <- bbMLE(x)\n  # updated the initialized vectors\n  alpha_values[i] <- estimate[\"alpha\"]\n  beta_values[i] <- estimate[\"beta\"]\n  theta_values[i] <- estimate[\"theta\"]\n}\n\n# mean and sd of beta (directly from lab)\nbeta_mean <- alpha_values / (alpha_values + beta_values)\nbeta_sd <- sqrt((alpha_values*beta_values)/((alpha_values + beta_values)^2 * (alpha_values + beta_values + 1)))\n\n# created dataframe with all the estimates (same as 5.2 with mean and sd now)\nresults <- data.frame(Player = players,\n                      alpha = alpha_values,\n                      beta = beta_values,\n                      theta = theta_values,\n                      mean = beta_mean,\n                      sd = beta_sd)\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Player     alpha      beta     theta      mean        sd\n1          Rob Cross 0.2682493 0.8125763  3.202028 0.2481893 0.2994525\n2       Gerwyn Price 0.2641368 0.9165646  3.175307 0.2237118 0.2822005\n3      Michael Smith 0.5343501 1.0677128  2.244502 0.3335388 0.2922818\n4       Luke Littler 0.2831778 0.3835995 10.797172 0.4246962 0.3828680\n5 Michael van Gerwen 0.2189583 0.4544064  5.001345 0.3251705 0.3621240\n6     Luke Humphries 0.3307220 0.4903559  6.390888 0.4027901 0.3634449\n7    Nathan Aspinall 2.4677443 4.3381444  1.492005 0.3625896 0.1720704\n8       Peter Wright 1.7855115 7.2890862  1.213638 0.1967593 0.1252497\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n# created initialized, empty vectors\nx_vals <- seq(0, 1, by = 0.01)\nx_values <- c()\ny_values <- c()\nplayer_values <- c()\n\n# created for loop to loop over players. Updated y values using alpha and beta from above and updated initialized vectors\nfor(i in 1:length(players)){\n  y_vals <- dbeta(x_vals, alpha_values[i], beta_values[i])\n  x_values <- c(x_values, x_vals)\n  y_values <- c(y_values, y_vals)\n  player_values <- c(player_values, rep(players[i], length(x_vals)))\n}\n\n# created dataframe with data from above\ndf <- data.frame(x = x_values, y = y_values, Player = player_values)\n\n# created plot\nggplot() +\n  geom_line(data = df, aes(x = x, y = y)) +\n  facet_wrap(~Player, ncol = 1, scales = \"free_y\") +\n  # my plot came back looking very squished so I looked up how to change the scale and it told me to include \"free_y\"\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Beta distributions for Dart players based on 2024 MLEs](Lab10WriteUp_files/figure-html/fig-dart_beta-distributions-1.png){#fig-dart_beta-distributions fig-align='center' width=480}\n:::\n:::\n\n\n \\normalsize\n\n\n## Executive Summary\nSummarize the work you've done here to provide a brief (200-300 word) data-driven summary of the 2024 Premier League season using your work in Lab 10. Your summary should be professional, clear, and all claims should be corroborated with statistical support.\n\n\nSolution:\nThe 2024 Premier League Darts season was able to be summarized by Altham's multiplicative binomial and beta binomial models. The estimated leg-winning probability (p in the binomial case and the beta means (alpha/(alpha+beta)) in the beta binomial case) correlated with how individuals players performed in the standings. Players towards the top of the standings like Like Littler and Like Humphries had both higher means (0.425 and 0.403 respectively) when compared with worse players like Peter Wright (0.197). The highest probabilities of winning individual legs directly coincided with winning more overall games and therefore placing higher in the standings. The standard deviation showed how consistent/variable the outcomes of specific players were. Players like Peter Wright and Nathan Aspinal had lower standard deviations (0.125 and 0.172 respectively), meaning they had more consistent outcomes. Players like Like Littler, Michael Van Gerwin and Luke Humphries had higher standard deviations (all around .36 or .38), implying they had more variability and showed their matches and outcomes were more unpredictable. Similarly to the Altham Multiplicative Binomial model, the theta in the beta-binomial model indicated how competitive or close matches typically were for certain players. For someone like Luke Littler, with a theta of 10.797, his games were typically more competitive than someone like Peter Wright who had a theta of 1.21. This likely implies that Luke Littler won a lot, but most of his games were very tight, while Peter Wright lost a lot and was getting blown out in almost all of his matches. In general, the models showed that higher ranked players win more legs on average and seem to have much closer and consistent performances when compared with those towards the bottom of the standings.",
    "supporting": [
      "Lab10WriteUp_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}