{
  "hash": "c4350133756a2b2ee088789d4e231a8b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Eight -- Probability # Title of the document\n\n# Bibliography Details\nbibliography: Lab8References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab8WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n# The Binomial and Negative Binomial Distributions\n\n## The Binomial Distribution\nIn many introductory courses, we make the simplifying assumption of independence in Bernoulli trials. For example, when playing best two-out-of-three legs in a darts match, we would assume Player A has an 70% chance of winning each leg. We write:\n$$X \\sim \\text{Binomial}(n=3, p=0.70)$$\nwhere\n\n* $X$ is the number of legs won\n* $n$ is the number of trials \n* $p$ is the probability of the event of interest\n\nOf note, it is not necessarily the case that the players play all three legs -- if either player wins legs one and two the match ends.\n\nThere are eight possible outcomes for Player A:\n\n* (win, win, \"win\") $\\longrightarrow$ Player A wins\n* (win, win, \"lose\") $\\longrightarrow$ Player A wins\n* (win, lose, win) $\\longrightarrow$ Player A wins\n* (win, lose, lose) $\\longrightarrow$ Player A loses\n* (lose, win, win)  $\\longrightarrow$ Player A wins\n* (lose, win, lose) $\\longrightarrow$ Player A loses\n* (lose, lose, \"win\") $\\longrightarrow$ Player A loses\n* (lose, lose, \"lose\") $\\longrightarrow$ Player A loses\n\n**Note**: I use quotations above to denote outcomes where the last match isn't actually played.\n\n**Use the Binomial distribution to compute the probability that Player A wins the match.  Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\nSolution:\nP(X >= 2)\n= 1 - P(X < 2)\n= 1 - P(X <= 1)\n= 1 - F(1)\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\n1 - pbinom(1, size = 3, prob = 0.70) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nsize <- 3 \nprob <- 0.70\nggdat <- tibble(x = -1:4) |>           # created data for PMF and CDF plots \n mutate(PMF = dbinom(x, size = size, prob = prob),\n        CDF = pbinom(x, size = size, prob = prob))\n\nPMF.plot <- ggplot() +                 # created the plot for the PMF\n  geom_linerange(data = ggdat,\n                 aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x>=2),\n                 aes(x = x, ymin = 0, ymax = PMF),\n                 color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=0:4) +\n  ylab(\"Probability\") +\n  theme_bw()\n\n# created CDF plot\nCDF.plot <- ggplot(ggdat, aes(x = x, y = CDF)) +\n  geom_step() +\n  geom_point() +\n  scale_x_continuous(breaks = 0:4) +\n  ylab(\"F(x) = P(X <= x)\") +\n  theme_bw()\n\nCDF.plot\nPMF.plot\n```\n\n::: {.cell-output-display}\n![PMF and CDF plots](Lab8WriteUp_files/figure-html/fig-box-billlength-1.png){#fig-box-billlength-1 fig-align='center' width=480}\n:::\n\n::: {.cell-output-display}\n![PMF and CDF plots](Lab8WriteUp_files/figure-html/fig-box-billlength-2.png){#fig-box-billlength-2 fig-align='center' width=480}\n:::\n:::\n\n\n \\normalsize\n\n\n## The Negative Binomial Distribution\nIn intermediate courses, we learn the Negative Binomial distribution that we use to model the number of \"failures\" until the $r$th success. Note that this approach still makes the simplifying assumption of independence in Bernoulli trials.\n\n**Specify the two cases necessary to compute the probability. Fully explain these probability statements in the context of a best two-out-of-three match and the Negative Binomial distribution. Finally, compute the probability that Player A wins the match and show you get the same result as the Binomial approach. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\nSolution:\nThe two cases in which player A can win are by having zero losses until the second win (W, W) where P(X = 0) and where player A has one loss before the second win (W, L, W or L, W, W) where P(X = 1). Overall the probability using the CDF becomes P(X <= 1) where X is the number of failures which will yield the same result as 1 - P(X = 1) where X is the number of wins.\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\npnbinom(1, size = 2, prob = 0.70) # P(X =< 1 |n=2, p=0.70). Answer: 0.784\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nsize <- 2 \nprob <- 0.70\nggdat <- tibble(x = -1:3) |>           # created data for PMF and CDF plots \n  mutate(PMF = dbinom(x, size = size, prob = prob),\n         CDF = pbinom(x, size = size, prob = prob))\n\nPMF.plot2 <- ggplot() +                 # created the plot for the PMF\n  geom_linerange(data = ggdat,\n                 aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x<=1),\n                 aes(x = x, ymin = 0, ymax = PMF),\n                 color = \"darkorchid2\", linewidth=2, alpha=0.50) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=0:3) +\n  ylab(\"Probability\") +\n  theme_bw()\n\nPMF.plot2\n```\n\n::: {.cell-output-display}\n![Negative Binomial PMF](Lab8WriteUp_files/figure-html/neg-binom-PMF-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n \\normalsize\n\n# The Beta Binomial Distribution\nOne approach to generalize this modeling is to use a Beta-Binomial distribution. This distribution arrises when we let $p$ be a random variable that follows a Beta distribution:\n\\begin{align*}\n  P &\\sim \\text{Beta}(\\alpha, \\beta)\\\\\n  X &\\sim \\text{Binomial}(n, P).\n\\end{align*}\nThis distribution is not part of base `R`, but is available using the `_bbinom` functions from the `extraDistr` package [@extraDistr].\n\nThe primary benefit is that the Beta-Binomial enables us to specify some uncertainty about the skill of Player A, as $p$ does not have to be fixed (e.g., $p=0.70$). Suppose the result of the best two-out-of-three match follows a Beta-Binomial distribution  where $\\alpha=7$ and $\\beta=3$.\n\n## The Beta Part\n1. **Plot the corresponding Beta distribution. Interpret the plot in the context of a best two-out-of-three match and the Binomial distribution.**\\\n**Hint**: The Beta distribution is available in base `R` via `_beta()`.\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nalpha <- 7\nbeta <- 3\n\nggdat <- tibble(p = seq(0,1, length.out=1000)) |>       # created data for beta plot \n  mutate(pdf = dbeta(p, shape1 = alpha, shape2 = beta))\n\nCDF.plot <- ggplot(ggdat) +\n  geom_line(aes(x = p, y = pdf)) +\n  xlab(\"Cumulative Probability (p)\") +\n  ylab(\"Frequency\") +\n  theme_bw()\n\nCDF.plot\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\nSolution:\nThe data distribution is right skewed and centered around 0.70 meaning that win probability is around 0.70. Most of the values of p fall between .60 and .80 with very few falling below .45.\n\n1. How does the Beta incorporate uncertainty about the skill of Player A? **Compute the mean and variance of the distribution.**\\\n**Hint**: You will find the `integrate(...)` function helpful here. \n\\begin{align*}\n  E(P) &= \\mu_P = \\int_{0}^1 p f_P(p) dp\\\\\n  var(P) &= \\sigma^2_P = \\int_{0}^1 (p-\\mu_P)^2 f_P(p) dp\\\\\n\\end{align*}\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean <- function(p){p * dbeta(p, 7, 3)} # created mean function\nintegrate(mean, 0, 1)$value             # used integrate function to find the mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7\n```\n\n\n:::\n\n```{.r .cell-code}\nu <- 0.7\nvar <- function(p){(p - u)^2 * dbeta(p, 7, 3)} # created variance function\nintegrate(var, 0, 1)$value                    # used integrate function to find the variance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01909091\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the probability that Player A has a win probability of exactly 0.70?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\\\n**Hint:** Think carefully about the properties of continuous distributions here.\n\nSolution:\nThe probability that Player A has a win probability of exactly 0.70 is 0.\nP(p = 0.70) = 0\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nalpha <- 7\nbeta <- 3\n\nggdat <- tibble(p = seq(0,1, length.out=1000)) |>       # created data for beta plot \n  mutate(pdf = dbeta(p, shape1 = alpha, shape2 = beta))\n\nggplot(ggdat) +\n  geom_line(aes(x = p, y = pdf)) +\n  geom_ribbon(data = ggdat |> filter(p == 0.7),\n              aes(x = p, ymin = 0, ymax = pdf),\n            fill = \"darkorchid2\", alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  xlab(\"Win Probability (p)\") +\n  ylab(\"Density\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the probability that Player A has a win probability of at least 0.50?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\n\nSolution:\nProbability Statement: P(p >= 0.50)\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pbeta(0.5, 7, 3) # 1 - P(p=0.5 |n=3, p=7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9101562\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nalpha <- 7\nbeta <- 3\n\nggdat <- tibble(p = seq(0,1, length.out=1000)) |>       # created data for beta plot \n  mutate(pdf = dbeta(p, shape1 = alpha, shape2 = beta))\n\nggplot(ggdat) +\n  geom_line(aes(x = p, y = pdf)) +\n  geom_ribbon(data = ggdat |> filter(p >= 0.5),\n              aes(x = p, ymin = 0, ymax = pdf),\n            fill = \"darkorchid2\", alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  xlab(\"Win Probability (p)\") +\n  ylab(\"Density\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the 90th percentile of Player A's win probability based on this Beta distribution? Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the percentile using `ggplot`.**\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqbeta(0.90, 7, 3) # P(p < p0.90) = 0.90\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8705027\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nalpha <- 7\nbeta <- 3\n\nggdat <- tibble(p = seq(0,1, length.out=1000)) |>       # created data for beta plot \n  mutate(pdf = dbeta(p, shape1 = alpha, shape2 = beta))\n\np90 <- qbeta(0.90, 7, 3)\n\nggplot(ggdat) +\n  geom_line(aes(x = p, y = pdf)) +\n  geom_ribbon(data = ggdat |> filter(p <= p90),\n              aes(x = p, ymin = 0, ymax = pdf),\n            fill = \"darkorchid2\", alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  xlab(\"Win Probability (p)\") +\n  ylab(\"Density\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\n\n## The Beta-Binomial Part\n**Compute the probability that Player A wins the match. Compare your result to the Binomial and Negative Binomial results. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`**\n\nSolution:\nProb(player A wins) = P(X >= 2) = P(X = 2) + P(X = 3)\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(extraDistr)\n\nprob_win <- dbbinom(2, size = 3, alpha = 7, beta = 3) + # prob Player A wins 2 matches\n            dbbinom(3, size = 3, alpha = 7, beta = 3) # prob Player A wins 3 matches\nprob_win\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7636364\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe binomial and negative binomial results yield a 0.784 probability which is higher than that of the beta binomial probability which is 0.764.\n\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(extraDistr)\nlibrary(tidyverse)\n\nggdat <- tibble(x =-1:3)|> # created data for PMF  plots\n  mutate(PMF = dbbinom(x, size = 3, alpha = 7, beta = 3))\n\nPMF.plot3 <- ggplot()+    # created the plot for the PMF\n  geom_linerange(data = ggdat,\n                aes(x = x,ymin = 0,ymax = PMF )) + \n  geom_linerange(data = ggdat|>filter(x >= 2),\n                aes(x = x,ymin = 0,ymax = PMF),\n                color =\"darkorchid2\", linewidth=2, alpha=0.50) + \n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\",breaks=0:3) +\n  ylab(\"Probability\") + \n  theme_bw()\n  \nPMF.plot3\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\n## The Why\nCheck the expected value and variance of each distribution.\n\nAnalytically, we have\n\\begin{align*}\n  E(X) &= np  &&var(X) = np(1-p) \\tag{Binomial Distribution}\\\\\n  E(X) &= n\\left(\\frac{\\alpha}{\\alpha+\\beta}\\right)  &&var(X) = \\frac{n \\alpha \\beta (\\alpha + \\beta + n)}{(\\alpha+\\beta)^2(\\alpha + \\beta + 1)} \\tag{Beta-Binomial Distribution}\n\\end{align*}\n\n**For each distribution, compute the mean number of legs won for player A.**\\\n**Hint**: You can perform the sum over the finite support set here. \n\\begin{align*}\n  E(X)   = \\mu_X    &= \\sum_{i=0}^3 i f_X(i)\\\\\n  var(X) = \\sigma_X &= \\sum_{i=0}^3 (i-\\mu_X) f_X(i)\n\\end{align*}\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(extraDistr)\n\nx <- 0:3\npmf <- dbinom(x, size = 3, prob = 0.70)\nsum(x * pmf)             # found mean for binomial distribution\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\nu <- sum(x * pmf)\nsum((x - u)^2 * pmf)     # found variance for binomial distribution\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.63\n```\n\n\n:::\n\n```{.r .cell-code}\nx <- 0:3\nbeta_pmf <- dbbinom(x, size = 3, alpha = 7, beta = 3)\nsum(x * beta_pmf)             # found mean for beta binomial distribution\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\nbeta_u <- sum(x * beta_pmf)\nsum((x - beta_u)^2 * beta_pmf)     # found variance for beta binomial distribution\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7445455\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n# Altham's Multiplicative Binomial Distribution\nWhile the Beta-Binomial enables us to model cases where winning has a clustering effect (e.g., a \"hot hand\").\n\n## Probability Mass Function\nThe mass function for this distribution is below. While it used to be available in the `MBD` package for `R`, this package is no longer available.\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}$$ \n\n**Write a function in `R` called `daltbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match**\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ndaltbinom <- function(x, n, p, theta){\n  i <- 0:n\n  c <- sum(choose(n, i) * p^i * (1-p)^(n-i) * theta^(i * (n-i)))      # created c variable to plug into pmf function\n\n  fxx <- choose(n, x) * p^x * (1-p)^(n-x) * theta^(x * (n-x))\n  return(fxx / c)\n}\n\nx_values <- 0:3\nthetas = c(0.50, 1, 1.50) \nggdat <- tibble(\n  x = rep(x_values, times = length(thetas)),        # got the x's to be used in the function\n  theta = rep(thetas, each = length(x_values))   # got the theta to be used in the function\n) |> \n  rowwise() |>\n  mutate(PMF = daltbinom(x, n = 3, p = 0.70, theta = theta)) |>\n  ungroup()\n\nggplot() +           # created plot for PMF\n  geom_linerange(data = ggdat,\n                 aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x >= 2),\n                 aes(x = x, ymin = 0, ymax = PMF),\n                 color = \"darkorchid2\", linewidth = 2, alpha = 0.5) +\n  facet_wrap(~theta) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"Number of Wins\", breaks = 0:3) +\n  ylab(\"Probability\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\nWhen theta = 0.5, 3 wins is by far the most probable outcome, and winning two or more times is signficantly more probable than not. When theta = 1, the most common number of wins is two, however, it is still more probabile to win two or more times. When theta = 1.5, the most common result is two wins with a 0.55 probability, and winning two or more times is likely. In all three theta cases, the probability of winning 0 games is close to zero. The probabilities that change are the probabilities of winning one or two games which both increase as theta increases.\n\n\n\n## Cumulative Distribution Function\n**Use your `daltbinom()` function to create a `paltbinom()` function for computing the CDF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$.**\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaltbinom <- function(x, n, p, theta){\n    # created function that sums probabilities of daltbinom function\n  sapply(x, function(end){\n    sum(daltbinom(0:end, n = n, p = p, theta = theta))\n    }) \n    # used sapply to apply the daltbinom function to a new vector\n}\n\nx_values <- 0:3\nthetas = c(0.50, 1, 1.50) \nggdat_cdf <- tibble(                                # created data to be plotted below\n  x = rep(x_values, times = length(thetas)),        # got the x's to be used in the function\n  theta = rep(thetas, each = length(x_values))      # got the theta to be used in the function\n) |> \n  mutate(CDF = mapply(function(x, theta) {\n    paltbinom(x, n = 3, p = 0.70, theta = theta)\n  }, x, theta))\n\n\nggplot(ggdat_cdf, aes(x = x, y = CDF)) +           # created plot for CDF\n  geom_step(direction = \"hv\", size = 0.5) +           # made sure cdf was plotted as a step function graph\n  geom_point(size = 1) +\n  facet_wrap(~theta) +\n  scale_x_continuous(\"Number of Wins\", breaks = -1:4) +\n  scale_y_continuous(\"P(X <= x)\", limits = c(0,1)) +   # created probability axis\n  ylab(\"Cumulative Probability\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\n## The Winning Probability\n**Compute the probability that Player A wins the match using Altham's Multiplicative Binomial Distribution. Compare your result to the Binomial and Negative Binomial results. Compare your results to the Beta-Binomial model, too. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\nSolution:\nThe probability statement using Altham's Multiplicative Binomial Distribution is: prob(win) = 1 - F(1)\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_win <- function(theta){                  # calculated the Altham Multiplicative Binomial Distribution probability of winning\n  1 - paltbinom(1, 3, 0.70, theta = theta)\n}\n\nprob_win(0.5)        # calculating win probabilities for each theta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8592417\n```\n\n\n:::\n\n```{.r .cell-code}\nprob_win(1) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n\n```{.r .cell-code}\nprob_win(1.5)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.746993\n```\n\n\n:::\n\n```{.r .cell-code}\ntable_data <- tibble(            # created a tibble to store the models and probabilities for plotting\n  model = c(\"Altham 0.5\", \"Altham 1\", \"Altham 1.5\",\n            \"Binom\", \"Nbinom\", \"BetaBinom\"),\n  probability = c(\n    prob_win(0.5),\n    prob_win(1),\n    prob_win(1.5),\n    0.784,\n    0.784,\n    0.763636)\n)\n\nggplot(table_data, aes(x = model, y = probability)) + # plotted models and their win probabilities \n  geom_col() +\n  xlab(\"Model\") +\n  ylab(\"Probability\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\nThe probability of winning using both the binomial and negative binomial distributions was 0.784. When using the beta-binomial distribution, the probability of winning was slightly lower at 0.764. Using the Altham model, when theta = 1, the probability of winning is the same as the binomial and negative binomial distributions (0.784). When theta = 0.5, the probability of winning is slightly higher (0.859) and when theta = 1.5, the probability of winning is slightly lower (0.747).\n\n\n\n# Altham's Multiplicative Beta-Binomial Distribution\nYou may have wondered -- \"Can we do the Beta thing with Altham's version of the Binomial Distribution?\" The answer is yes!\n\n## Probability Mass Function\nThe mass function for this distribution is below. \n$$f_X(x) = \\left[\\int_{0}^1 dp\n\\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right)\\right]I(x \\in \\{0, 1, ..., n\\})$$\n\n**Write a function in `R` called `daltbbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $\\alpha=7$ and $\\beta=3$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match.**\\\n\n**Hint**: You can use the `integrate()` in `R` to compute the integral. Note that this requires the function to be vectorized -- it should be unless you have added any block conditionals. \n\nSolution:\n\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ndaltbbinom <- function(x, n, a, b, theta){      # created function daltbbinom\n  # If x not a whole number or out of bounds, prob is 0\n  if (x %% 1 != 0 | x < 0 | x > n) {\n    return(0)\n  }\n  # created function integrand\n  integrand <- function(p) {\n    c_vec <- sapply(p, function(p_val) {\n      i <- 0:n  \n      sum(choose(n, i) * p_val^i * (1-p_val)^(n-i) * theta^(i * (n-i)))\n    })      \n    # created c variable to plug into pmf function (taken from daltbinom function in 3.1)\n\n    altham_part <- (1/c_vec) * choose(n, x) * p^x * (1-p)^(n-x) * theta^(x * (n - x)) \n      # created the altham PMF part directly from the lab\n\n    beta_part <- dbeta(p, a, b) # created the beta density part directly from the lab\n\n    return(altham_part * beta_part)\n  }\n  return(integrate(integrand, lower = 0, upper = 1)$value)   # used integrate to apply my integrand function from above \n}\n           \n\nx_values <- 0:3\nthetas = c(0.50, 1, 1.50) \nggdat_altbb <- tibble(                              # created data to be plotted below\n  x = rep(x_values, times = length(thetas)),        # got the x's to be used in the function\n  theta = rep(thetas, each = length(x_values))      # got the theta to be used in the function\n) |> \n  rowwise() |>\n  mutate(PMF = daltbbinom(x, n = 3, a = 7, b = 3, theta = theta)) |>                                   \n  ungroup()\n  # took this section almost directly from the daltbinom part in 3.1\n\nggplot(ggdat_altbb, aes(x = x, y = PMF)) +           # created plot for PMF\n  geom_linerange(aes(ymin = 0, ymax = PMF)) +           \n  geom_point() +\n  facet_wrap(~theta) +\n  scale_x_continuous(\"Number of Wins\", breaks = 0:3) +\n  ylab(\"Probability\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\nWhen theta = 0.5, the probability of winning three games is extremely high at 0.62, and the probability of winning at least two out of 3 games is more probable than not. When theta = 1, the combined probability of winning two or three games is greater than the combined probability of winning 0 or one games with the probability of winning either two or three games each at around 0.4. When theta = 1.5, the most probable outcome is winning two games, but the combined probability of winning two or three games is greater than the combined probability of winning 0 or one games.\n\n# A Comparison\nCompute the probabilities for all outcomes for Player A.\n\n* Loses 0-2 (LL\"L\", LL\"W\")\n* Loses 1-2 (WLL, LWL)\n* Wins 2-0 (WW\"W\", WW\"L\")\n* Wins 2-1 (LWW, WLW)\n\n**Note**: You'll need to define these outcomes in terms of the random variable. \n\n**Create a bar plot (or column plot) using `ggplot` to show the probability of each outcome under the following conditions:**\n\n* **Binomial**\n* **Negative Binomial**\\\n**Note**: You can compute the lose probabilities the same way as the win probabilities using success probability ($1-p$)\n* **Beta-Binomial**\n* **Althman Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n* **Althman Beta-Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n\n**Comment on the differences in the context of a best two-out-of-three match.**\n\nSolution:\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\np <- 0.7             # created parameters for win probabilities of each round based off 1.1\nq <- 1 - p \n\nProb_LL <- q*q       # created probabilities for each scenario (if 2 wins or 2 losses in first two games, third game not played)\nProb_WLL <- p*q*q\nProb_LWL <- q*p*q\nProb_WW <- p*p\nProb_LWW <- q*p*p\nProb_WLW <- p*q*p\n\n\nbinomial_probabilities <- c(   # created vector with prob of each outcome for binomial condition\n  \"Lose 0-2\" = Prob_LL,\n  \"Lose 1-2\" = Prob_WLL + Prob_LWL,\n  \"Win 2-0\"  = Prob_WW,\n  \"Win 2-1\"  = Prob_LWW + Prob_WLW\n)\nbinomial_probabilities\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLose 0-2 Lose 1-2  Win 2-0  Win 2-1 \n   0.090    0.126    0.490    0.294 \n```\n\n\n:::\n\n```{.r .cell-code}\n# created probabilities for negative binomial condition\nProb_LL <- q*q\nProb_1_2 <- choose(2,1)*q*q*p # prob that you win once before your second loss\nProb_WW <- p*p\nProb_2_1 <- choose(2,1)*p*p*q # prob that you lose once before your second win\n\nnegbinomial_probs <- c(          # created vector with prob of each outcome for negativebinomial condition\n  \"Lose 0-2\" = Prob_LL,\n  \"Lose 1-2\" = Prob_1_2,\n  \"Win 2-0\"  = Prob_WW,\n  \"Win 2-1\"  = Prob_2_1\n)\nnegbinomial_probs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLose 0-2 Lose 1-2  Win 2-0  Win 2-1 \n   0.090    0.126    0.490    0.294 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Beta-Binomial part:\na <- 7       # parameters from quesition 2\nb <- 3\nbeta_binom <- function(c, d){           # created beta binomial function that allows me to imput values to represent p^c * (1-p)^d \n  beta(a + c, b + d) / beta(a, b)\n}\n\nProb_LL <- beta_binom(0, 2)       # created probabilities for each scenario (here is 0 wins, 2 losses)\nProb_WLL <- beta_binom(1, 2)\nProb_LWL <- beta_binom(1, 2)\nProb_WW <- beta_binom(2, 0)\nProb_LWW <- beta_binom(2, 1)\nProb_WLW <- beta_binom(2, 1)\n\nbeta_binomial_probs <- c(          # created vector with prob of each outcome for beta binomial condition\n  \"Lose 0-2\" = Prob_LL,\n  \"Lose 1-2\" = Prob_WLL + Prob_LWL,\n  \"Win 2-0\"  = Prob_WW,\n  \"Win 2-1\"  = Prob_LWW + Prob_WLW\n)\nbeta_binomial_probs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Lose 0-2  Lose 1-2   Win 2-0   Win 2-1 \n0.1090909 0.1272727 0.5090909 0.2545455 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Althman Part:\n# (0.5 theta)\ntheta <- 0.5\n# created probs using the function in 3.1 (p^x * (1-p)^(n-x) * theta^(x(n-x)))\nProb_LL  <- q*q\nProb_WLL <- p*q*q* theta^2    # (p * q^2 * theta^(1*2))\nProb_LWL <- q*p*q * theta^2\nProb_WW  <- p*p\nProb_LWW <- q*p*p * theta^2\nProb_WLW <- p*q*p * theta^2\n\naltham_05_probs <- c(          # created vector with prob of each outcome for beta binomial condition\n  \"Lose 0-2\" = Prob_LL,\n  \"Lose 1-2\" = Prob_WLL + Prob_LWL,\n  \"Win 2-0\"  = Prob_WW,\n  \"Win 2-1\"  = Prob_LWW + Prob_WLW\n)\naltham_05 <- altham_05_probs / sum(altham_05_probs) # made it so the sums of the probabilities added to one because they weren't doing it before\naltham_05\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Lose 0-2  Lose 1-2   Win 2-0   Win 2-1 \n0.1313869 0.0459854 0.7153285 0.1072993 \n```\n\n\n:::\n\n```{.r .cell-code}\n# (1.5 theta)\ntheta <- 1.5\n# created probs using the function in 3.1 (p^x * (1-p)^(n-x) * theta^(x(n-x)))\nProb_LL  <- q*q\nProb_WLL <- p*q*q* theta^2    # (p * q^2 * theta^(1*2))\nProb_LWL <- q*p*q * theta^2\nProb_WW  <- p*p\nProb_LWW <- q*p*p * theta^2\nProb_WLW <- p*q*p * theta^2\n\naltham_15_probs <- c(          # created vector with prob of each outcome for beta binomial condition\n  \"Lose 0-2\" = Prob_LL,\n  \"Lose 1-2\" = Prob_WLL + Prob_LWL,\n  \"Win 2-0\"  = Prob_WW,\n  \"Win 2-1\"  = Prob_LWW + Prob_WLW\n)\naltham_15 <- altham_15_probs / sum(altham_15_probs) # made it so the sums of the probabilities added to one because they weren't doing it before\naltham_15\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Lose 0-2   Lose 1-2    Win 2-0    Win 2-1 \n0.05901639 0.18590164 0.32131148 0.43377049 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Althman Beta Part:\n# (0.5 theta)\na <- 7\nb <- 3\nalth_bb <- function(c, d){  # created beta binomial function that allows me to imput values to represent p^c * (1-p)^d \n  beta(a + c, b + d) / beta(a, b)\n}\ntheta <- 0.5\nProb_LL  <- alth_bb(0,2)\nProb_WLL <- alth_bb(1,2) * theta^2\nProb_LWL <- alth_bb(1,2) * theta^2\nProb_WW  <- alth_bb(2,0)\nProb_LWW <- alth_bb(2,1) * theta^2\nProb_WLW <- alth_bb(2,1) * theta^2\n\naltham_bb_05_probs <- c(          # created vector with prob of each outcome for altham beta binomial condition (.5 theta)\n  \"Lose 0-2\" = Prob_LL,\n  \"Lose 1-2\" = Prob_WLL + Prob_LWL,\n  \"Win 2-0\"  = Prob_WW,\n  \"Win 2-1\"  = Prob_LWW + Prob_WLW\n)\n# # made it so the sums of the probabilities added to one because they weren't doing it before\naltham_bb_05 <- altham_bb_05_probs/sum(altham_bb_05_probs)\naltham_bb_05\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Lose 0-2   Lose 1-2    Win 2-0    Win 2-1 \n0.15286624 0.04458599 0.71337580 0.08917197 \n```\n\n\n:::\n\n```{.r .cell-code}\n# (1.5 theta)\ntheta <- 1.5\nProb_LL  <- alth_bb(0,2)\nProb_WLL <- alth_bb(1,2) * theta^2\nProb_LWL <- alth_bb(1,2) * theta^2\nProb_WW  <- alth_bb(2,0)\nProb_LWW <- alth_bb(2,1) * theta^2\nProb_WLW <- alth_bb(2,1) * theta^2\n\naltham_bb_15_probs <- c(          # created vector with prob of each outcome for altham beta binomial condition (.5 theta)\n  \"Lose 0-2\" = Prob_LL,\n  \"Lose 1-2\" = Prob_WLL + Prob_LWL,\n  \"Win 2-0\"  = Prob_WW,\n  \"Win 2-1\"  = Prob_LWW + Prob_WLW\n)\n# # made it so the sums of the probabilities added to one because they weren't doing it before\naltham_bb_15 <- altham_bb_15_probs/sum(altham_bb_15_probs)\naltham_bb_15\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Lose 0-2   Lose 1-2    Win 2-0    Win 2-1 \n0.07384615 0.19384615 0.34461538 0.38769231 \n```\n\n\n:::\n\n```{.r .cell-code}\n# created dataframe containing all of my probabilities to use in plot \ndf <- tibble(\n  Outcome = c(\"Lose 0-2\",\"Lose 1-2\",\"Win 2-0\",\"Win 2-1\"),\n  Binomial = binomial_probabilities,\n  NegativeBinomial = negbinomial_probs,\n  BetaBinomial = beta_binomial_probs,\n  Altham_0_5 = altham_05,\n  Altham_1_5 = altham_15,\n  AlthamBB_0_5 = altham_bb_05,\n  AlthamBB_1_5 = altham_bb_15\n)\n\n# transposed the dataframe from wide to long\ndf_new <- reshape(\n  as.data.frame(df), # had to convert tibble to a dataframe because there was an error when I was trying to do it as a tibble\n  varying = list(names(df)[-1]), # removes the first column of my dataframe (Outcome) for the reshaping process\n  v.names = \"Probability\", # names of variables in the long format that correspond to multiple variables in the wide format\n  timevar = \"Model\", # differentiates multiple records from the same group or individual\n  times = names(df)[-1],\n  direction = \"long\"\n)\n\ndf_new <- df_new |>\n  select(-id) # id column created when I reshaped the dataframe, so I removed the excess column\n\n# created bar plot using data from the transposed dataframe\nggplot(df_new, aes(x = Outcome, y = Probability, fill = Model)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\nIn a best two out of three match, it seems like in every distribution, player A is more likely to win than lose, however in both the Altham and Altham Beta Binomial distributions, a sweep (either 2-0, or 0-2) is more likely to occur than in the other distributions when theta is equal to 0.5 and a sweep is less likely to occur when theta is equal to 1.5.  ",
    "supporting": [
      "Lab8WriteUp_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}